# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'UUChatTableView' do
    pod 'AVOSCloud'
    pod 'AVOSCloudIM'
end

target 'UUChatTableViewTests' do

end

